name: Jekyll Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: jekyll build and rsync
      uses: foureyes/jekyll-rsync-action@v1.1.0
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        DEST_USERNAME: ${{ secrets.DEST_USERNAME }}
        DEST_HOST: ${{ secrets.DEST_HOST }}
        DEST_PATH: ${{ secrets.DEST_PATH }}
